name: "Build"
on:
  push:
    branches: ["master"]
jobs:
  wasm:
    name: "Build web client"
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
      - uses: "dtolnay/rust-toolchain@stable"
        with:
          target: "wasm32-unknown-unknown"
      - run: "wget -O - https://github.com/trunk-rs/trunk/releases/download/v0.21.5/trunk-x86_64-unknown-linux-gnu.tar.gz | tar xz"
      - run: "./trunk build --release=true --public-url=/omniatc web/index.html"
      - id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
  deploy:
    environment:
      name: "github-pages"
      url: "${{ steps.deployment.outputs.page_url }}"
    permissions:
      contents: read
      pages: write
      id-token: write
    name: "Deploy pages"
    runs-on: ubuntu-latest
    needs: "wasm"
    steps:
      - name: "Deploy to GitHub Pages"
        uses: "actions/deploy-pages@v4"
