name: "Build"
on:
  push:
    branches: ["master", "ci-test"]
jobs:
  wasm:
    name: "Build web client"
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
      - uses: "dtolnay/rust-toolchain@stable"
        with:
          target: "wasm32-unknown-unknown"
      - run: "wget -O - https://github.com/trunk-rs/trunk/releases/download/v0.21.5/trunk-x86_64-unknown-linux-gnu.tar.gz | tar xz"
      - run: "./trunk build --release=true"
      - uses: "actions/upload-artifact@v4"
        with:
          name: "wasm"
          path: "dist"
  assets:
    name: "Preprocess assets"
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
      - uses: "dtolnay/rust-toolchain@stable"
      - run: "cargo run -p omniatc-maps"
      - uses: "actions/upload-artifact@v4"
        with:
          name: "assets"
          path: "assets"
  bin:
    name: "Build desktop client"
    strategy:
      matrix:
        target:
          - os: "ubuntu-latest"
            target: "x86_64-unknown-linux-gnu"
          - os: "ubuntu-latest"
            target: "aarch64-unknown-linux-gnu"
          - os: "macos-latest"
            target: "x86_64-apple-darwin"
          - os: "macos-latest"
            target: "aarch64-apple-darwin"
          - os: "windows-latest"
            target: "x86_64-pc-windows-msvc"
            suffix: ".exe"
          - os: "windows-latest"
            target: "aarch64-pc-windows-msvc"
            suffix: ".exe"
    runs-on: "${{matrix.target.os}}"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "houseabsolute/actions-rust-cross@v0"
        with:
          target: "${{matrix.target.target}}"
          args: "--release --no-default-features --bin omniatc-client"
      - uses: "actions/upload-artifact@v4"
        with:
          name: "bin-${{matrix.target.target}}"
          path: "target/${{matrix.target.target}}/release/omniatc-client${{matrix.target.suffix}}"
  prepare-pages:
    name: "Prepare GitHub pages"
    runs-on: ubuntu-latest
    needs: ["wasm", "assets", "bin"]
    steps:
      - uses: "actions/download-artifact@v4"
        with:
          path: "pages"
      - run: "cp -r pages/bin-* pages/wasm"
      - run: "rm -r pages/wasm/assets && mv pages/assets pages/wasm/assets"
      - run: "tree pages/wasm"
      - id: deployment
        uses: "actions/upload-pages-artifact@v3"
        with:
          path: "pages/wasm"
  deploy:
    environment:
      name: "github-pages"
      url: "${{ steps.deployment.outputs.page_url }}"
    permissions:
      contents: read
      pages: write
      id-token: write
    name: "Deploy pages"
    runs-on: ubuntu-latest
    needs: ["prepare-pages"]
    steps:
      - name: "Deploy to GitHub Pages"
        uses: "actions/deploy-pages@v4"
